### ISSUE TITLE
a lot of errors when build

### ISSUE THREAD

**Issue by mixxr** [makinacorpus/angular2-schema-form#16]
a lot of error when
```
npm run build
```
this is just an extract (the first couple of errors), **maybe typings.json is needed?**
thx
```
ERROR in ./src/schema-form/defaultwidgets/array/array.widget.ts
Module not found: Error: Cannot resolve module '@angular/core' in /root/git/angu
lar2-schema-form/src/schema-form/defaultwidgets/array
resolve module @angular/core in /root/git/angular2-schema-form/src/schema-form/d
efaultwidgets/array
  looking for modules in /root/git/angular2-schema-form/node_modules
    /root/git/angular2-schema-form/node_modules/@angular doesn't exist (module a
s directory)
[/root/git/angular2-schema-form/node_modules/@angular]
 @ ./src/schema-form/defaultwidgets/array/array.widget.ts 2:13-37

ERROR in ./src/schema-form/defaultwidgets/object/object.widget.ts
Module not found: Error: Cannot resolve module '@angular/core' in /root/git/angu
lar2-schema-form/src/schema-form/defaultwidgets/object
```

**Comment by SBats** [comment]
Hi @mixxr ,
we recently changed a few things about dependencies and typings on the project in order to follow angular 2 latest version. 

Could you please check that :
- you have the peer dependencies installed ? (if you're not sure, you can run `install-peer.sh` script at the repository's root)
- you did `npm install` again after updating the project as typings are now handled as common npm modules. (`typings` folder and `typings.json` file aren't used anymore, so you can delete they're still there)

**Comment by mixxr** [comment]
it works thanks
